### ISSUE TITLE
Why is it that every time I place a mob shard it destroys itself?

### ISSUE THREAD

**Issue by seriousfreezing** [Sweetmimike-mods/perfectmobfarm#1]
I put it in my world config to be more than +999999 durability!

**Comment by aureliencarpentier** [comment]
What kind of mob shard do you put in your mob farm ?

**Comment by seriousfreezing** [comment]
I at first put an iron golem and it just disappeared after seconds. Then I tested it with a cow and it was gone after seconds too.

**Comment by aureliencarpentier** [comment]
Sorry, I didn't succeed to reproduce your bug. Can you give me more details (Minecraft and Forge version, others mods you use, etc ...) ?

**Comment by seriousfreezing** [comment]
Modpack:
Minecraft 1.18.2
Forge 40.1.54

perfectmobfarm-1.18.2-1.2.0
bonsaitrees3-3.1.0
CobbleForDays-1.5.1
easy_piglins-1.18.2-1.0.0
easy_villagers-1.18.2-1.0.5
getinthebucketmod-4.0.1
jei-1.18.2-9.7.0.209
libnonymous-2.1.0

Config (in saves):
[perfectmobfarm-server.toml.zip](https://github.com/Sweetmimike-mods/perfectmobfarm/files/9481393/perfectmobfarm-server.toml.zip)

Steps to reproduce:
1. Create a super flat world.
2. Create the mobfarm in survival mode.
3. Place it in the world.
4. Make a lasso (detail: I made and use a datapack that changes the recipe of this item)
5. Get an iron golem or cow with the lasso.
6. Place it on the mobfarm.
7. Wait a few seconds.
8. There, your entity disappears from mobfarm!
